environments:
  example:
    environment_variables:
      EXAMPLE_DEPLOYMENT: testing
    pipelines:
      - pipeline-C
pipelines:
  testpipeline:
    group: initital
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/aetorres/c_test.git
        branch: master
    stages:
      - build: build
          jobs:
            build: compile
              tasks:
               - exec: # indicates type of task
                   command: /bin/bash
                   arguments:
                    - "-c"
                    - "gcc -Wall test.c -o test"
